#!/usr/bin/env python3
"""PreToolUse guard: refuse hand-edits of generated or secret-bearing files.

Claude Code passes the tool call as JSON on stdin. Exit code 2 blocks the call
and feeds stderr back to the model, so the message doubles as the instruction
for what to run instead.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# posix path (or path prefix, when it ends with "/") -> how to regenerate it.
GENERATED: dict[str, str] = {
    "sdk/openapi.json": (
        "generated by `python scripts/export_openapi.py` and gated by the "
        "`openapi_drift` CI job — change the routers/models, then regenerate"
    ),
    "mkdocs-site/docs/api/specs/openapi.json": (
        "generated by `python scripts/export_openapi.py "
        "mkdocs-site/docs/api/specs/openapi.json` — change the routers/models, "
        "then regenerate"
    ),
    "uv.lock": (
        "generated by `uv lock` and gated by the `uv_lock_check` CI job — edit "
        "the dependency ranges in pyproject.toml, then re-lock"
    ),
    "scripts/file_size_baseline.json": (
        "the 500-line ratchet baseline: it only ever shrinks. A new entry is a "
        "regression — split the module instead. After a legitimate split run "
        "`python scripts/check_file_size.py --update-baseline`"
    ),
}

GENERATED_PREFIXES: tuple[str, ...] = (
    "plugins/baselithbot/ui/dist/",
    "backstage-portal/",
)


def _reject(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(2)


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return

    raw_path = payload.get("tool_input", {}).get("file_path")
    if not raw_path:
        return

    repo_root = Path(__file__).resolve().parents[2]
    try:
        relative = Path(raw_path).resolve().relative_to(repo_root).as_posix()
    except ValueError:
        return

    name = Path(relative).name
    if name == ".env" or (name.startswith(".env.") and not name.endswith(".example")):
        _reject(
            f"BLOCKED: {relative} holds real credentials and is gitignored. "
            "Edit the committed `.env.example` template instead, and let the "
            "user fill in the secret value themselves."
        )

    reason = GENERATED.get(relative)
    if reason is not None:
        _reject(f"BLOCKED: {relative} is {reason}. Do not hand-edit it.")

    if relative.startswith(GENERATED_PREFIXES):
        _reject(
            f"BLOCKED: {relative} is build output, not source. Edit the source "
            "tree and rebuild."
        )


if __name__ == "__main__":
    main()
