"""What ``baselith init`` does after copying a template's files.

Split out of :mod:`core.cli.commands.init` for the module size cap. Every
template — built-in or directory — gets the same three things, so a new
project starts on a laptop with ``baselith run`` and nothing else:

* a ``.env`` from the development profile of
  :mod:`core.cli.commands.env_profiles` (the profile ``baselith config env``
  applies), with a ``SECRET_KEY`` and ``DB_PASSWORD`` generated for this
  project alone and file mode ``0600``;
* a ``.gitignore`` that keeps that ``.env`` and the local data out of git;
* the data directories the server's preflight and ``baselith doctor`` check.
"""

from __future__ import annotations

from pathlib import Path

from core.cli.commands.env_profiles import DEV_DEFAULTS, write_project_env

#: Comment block at the top of a generated ``.env``. The keys below it come
#: from ``DEV_DEFAULTS`` plus the generated secrets.
ENV_HEADER = """# {project_name} — local development settings, generated by `baselith init`.
#
# SECRET_KEY and DB_PASSWORD below were generated for this project only.
# Keep this file private (it is created with mode 0600 and listed in
# .gitignore) and never reuse these values in another environment.
#
# APP_ENV=development: production refuses to start without TRUSTED_HOSTS for
# its public hostname, JWT claim binding and a reachable database. Deploy
# with your own production settings, not this file.
#
# LLM_PROVIDER=ollama needs no API key: install Ollama, then
# `ollama pull llama3.2`. For a hosted model set LLM_PROVIDER (openai,
# anthropic, gemini, ...), LLM_MODEL and LLM_API_KEY.
#
# PostgreSQL, Redis and Qdrant point at localhost (`docker compose up -d` when
# the project ships a docker-compose.yml). The server starts without them and
# reports what is missing on /health/ready.
#
# `baselith config env` adds any setting missing here without touching the
# values already set.
"""

#: Entries every generated project's ``.gitignore`` must carry.
GITIGNORE_ENTRIES = (".env", "data/")

#: The data directories ``baselith doctor`` and the ``baselith run`` preflight
#: require under ``CORE_DATA_DIR`` (``./data`` in the development profile).
DATA_DIRS = ("data", "data/catalog", "data/compliance")


def write_env(project_path: Path, project_name: str) -> list[str]:
    """Write the project's ``.env`` from the development profile.

    Args:
        project_path: The new project directory.
        project_name: Its name, for the header comment.

    Returns:
        The keys written.

    Raises:
        FileExistsError: The project already has a ``.env``.
    """
    header = ENV_HEADER.replace("{project_name}", project_name)
    return write_project_env(project_path / ".env", header)


def ensure_gitignore(project_path: Path) -> list[str]:
    """Add the entries of :data:`GITIGNORE_ENTRIES` the ``.gitignore`` lacks.

    Args:
        project_path: The new project directory.

    Returns:
        The entries added.
    """
    path = project_path / ".gitignore"
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    present = {line.strip() for line in text.splitlines()}
    missing = [entry for entry in GITIGNORE_ENTRIES if entry not in present]
    if missing:
        if text and not text.endswith("\n"):
            text += "\n"
        path.write_text(text + "".join(f"{entry}\n" for entry in missing))
    return missing


def ensure_data_dirs(project_path: Path) -> None:
    """Create the data directories the server and ``baselith doctor`` check."""
    for name in DATA_DIRS:
        (project_path / name).mkdir(parents=True, exist_ok=True)


def finish_project(project_path: Path, project_name: str) -> None:
    """Give a freshly copied template its ``.env``, ``.gitignore`` and data dirs.

    Args:
        project_path: The new project directory.
        project_name: Its name.
    """
    write_env(project_path, project_name)
    ensure_gitignore(project_path)
    ensure_data_dirs(project_path)


def next_steps(files: dict[str, str]) -> list[str]:
    """The exact commands that start what a template wrote, in order.

    ``baselith run`` serves ``backend.py``, so it is named only for a template
    that has one; the panel used to name it unconditionally. The model pull
    comes *before* the server: ``baselith run``'s preflight refuses to start
    while the model ``LLM_MODEL`` names is missing from Ollama.

    Args:
        files: The template's files, by relative path.

    Returns:
        Rich-markup lines for the "Next steps" panel, ``cd`` excluded.
    """
    steps: list[str] = []
    if "pyproject.toml" in files:
        steps.append("[bold]pip[/bold] install -e .")
    elif "requirements.txt" in files:
        steps.append("[bold]pip[/bold] install -r requirements.txt")
    if "docker-compose.yml" in files:
        steps.append(
            "[bold]docker[/bold] compose up -d  [dim]# optional: local services[/dim]"
        )
    serves = "backend.py" in files or "main.py" in files
    if serves or "app/agent.py" in files:
        steps.append(
            f"[bold]ollama[/bold] pull {DEV_DEFAULTS['LLM_MODEL']}"
            "  [dim]# LLM_PROVIDER=ollama: a local model, no API key[/dim]"
        )
    health = "  [dim]# then open http://127.0.0.1:8000/health[/dim]"
    if "backend.py" in files:
        steps.append(f"[bold]baselith[/bold] run{health}")
    elif "main.py" in files:
        steps.append(f"[bold]python[/bold] main.py{health}")
    elif "agent.py" in files:
        steps.append("[bold]python[/bold] agent.py")
    if "app/agent.py" in files:
        steps.append("[bold]python[/bold] -m app.agent  [dim]# ask the agent[/dim]")
    return steps


__all__ = [
    "DATA_DIRS",
    "ENV_HEADER",
    "GITIGNORE_ENTRIES",
    "ensure_data_dirs",
    "ensure_gitignore",
    "finish_project",
    "next_steps",
    "write_env",
]
