"""The built-in ``baselith init`` template, ``minimal``.

Split out of :mod:`core.cli.commands.init` for the module size cap. The
directory starters (``rag-system``, ``multi-agent-collab``, ...) live under
``templates/`` and ship in the wheel as ``core/cli/scaffold_templates``; this
one is embedded so ``baselith init`` always has a working template, even from
an install that carries no data files.

The template deliberately has no ``.env``: :mod:`core.cli.commands.init_setup`
writes one for every template from the development profile, with secrets
generated for that project alone.
"""

_AGENT_MODULE = '''"""The project's first agent.

Run it with ``python -m app.agent``. ``Agent.run`` is a coroutine, so it needs
a running event loop — hence ``asyncio.run`` at the bottom.
"""

import asyncio

from baselith import Agent


async def current_time(timezone: str = "UTC") -> str:
    """Return the current time in a timezone.

    Args:
        timezone: IANA timezone name, e.g. "Europe/Rome".
    """
    from datetime import datetime
    from zoneinfo import ZoneInfo

    return datetime.now(ZoneInfo(timezone)).isoformat()


agent = Agent(
    system_prompt="You are a concise assistant.",
    tools=[current_time],
)


async def main() -> None:
    """Ask the agent one question and print the answer."""
    result = await agent.run("What time is it in Europe/Rome?")
    print(result.text)


if __name__ == "__main__":
    asyncio.run(main())
'''

_AGENT_TEST_MODULE = '''"""The scaffolded agent is importable and declares its tool."""

from app.agent import agent


def test_agent_exposes_its_tool() -> None:
    assert "current_time" in agent.tool_names
'''

#: ``baselith run`` serves ``backend:app`` from the project root.
BACKEND_MODULE = '''"""The project's API server: the BaselithCore app, with this project's plugins.

Start it with ``baselith run`` (preflight checks, then uvicorn on HOST:PORT
from ``.env``) or ``uvicorn backend:app``. Settings come from ``.env`` in the
directory you start it from.
"""

from baselith import create_app

app = create_app()
'''

#: Local backing services for the development profile in ``.env``. Ports are
#: published on loopback only; the database password is the one ``baselith
#: init`` generated into ``.env`` (Compose reads ``.env`` for interpolation).
SERVICES_COMPOSE = """# Local services for development: `docker compose up -d`.
# Credentials come from .env (DB_USER / DB_PASSWORD / DB_NAME), which
# `baselith init` generated for this project.
services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${DB_NAME:-baselithcore}
      POSTGRES_USER: ${DB_USER:-baselithcore}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?set DB_PASSWORD in .env}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 10

  # Redis protocol (cache, queue) plus the graph module GRAPH_DB_URL uses.
  redis:
    image: falkordb/falkordb:v4.20.4
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:v1.19.1
    ports:
      - '127.0.0.1:6333:6333'
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
"""

_README = """# {project_name}

A BaselithCore project.

## Quick start

```bash
pip install -e .
ollama pull llama3.2    # the local model LLM_MODEL names (https://ollama.com)
baselith run            # API on http://127.0.0.1:8000 — try /health and /docs
```

`baselith run` checks the configuration first and refuses to start while the
model is missing; it does not need the database or Redis.

`.env` was generated by `baselith init` for local development: `APP_ENV=development`,
a random `SECRET_KEY` and `DB_PASSWORD` for this project only (file mode 0600,
ignored by git), loopback-only `HOST` and `TRUSTED_HOSTS`, and
`LLM_PROVIDER=ollama`, the provider that needs no API key.

The server starts without any backing service and reports what is missing on
`/health/ready`. To run the full stack locally:

```bash
docker compose up -d    # PostgreSQL, Redis (FalkorDB), Qdrant on localhost
python -m app.agent     # ask the agent one question
baselith doctor         # check configuration and services
```

To use a hosted model instead, set `LLM_PROVIDER` (e.g. `openai`), `LLM_MODEL`
and `LLM_API_KEY` in `.env`.

## Layout

```
{project_name}/
├── app/                # Your application code; app/agent.py is the first agent
├── plugins/            # Your plugins — domain logic belongs here
├── tests/              # Your tests
├── backend.py          # The API server (`baselith run`)
├── docker-compose.yml  # Local PostgreSQL / Redis / Qdrant
├── .env                # Local configuration (generated, never commit it)
└── pyproject.toml
```

The framework is a dependency (`baselith-core`), not a directory inside this
project. Import it as `baselith`:

```python
from baselith import Agent
```
"""

#: Templates the CLI can scaffold without a checkout of this repository.
#:
#: ``full`` and ``chat-only`` used to sit here with an empty ``files`` dict.
#: The scaffolder only checked that ``files`` *was* a dict, so each of them
#: created an empty directory and then printed "Created project at ..." — and
#: the interactive prompt offered both by name. They are removed rather than
#: stubbed: a template that produces nothing is worse than one that is not
#: offered.
PROJECT_TEMPLATES = {
    "minimal": {
        "description": "Minimal project: one agent and the API server",
        "files": {
            "README.md": _README,
            "pyproject.toml": """[project]
name = "{project_name}"
version = "0.1.0"
description = "A BaselithCore project"
requires-python = ">=3.12"
dependencies = [
    "baselith-core>={framework_version}",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "pytest-asyncio"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*", "plugins*"]
""",
            ".gitignore": """__pycache__/
*.py[cod]
.venv/
.env
data/
.pytest_cache/
""",
            "backend.py": BACKEND_MODULE,
            "docker-compose.yml": SERVICES_COMPOSE,
            "app/__init__.py": '"""Application module."""\n',
            "app/agent.py": _AGENT_MODULE,
            "plugins/.gitkeep": "",
            "tests/__init__.py": '"""Test module."""\n',
            "tests/test_agent.py": _AGENT_TEST_MODULE,
        },
    },
}

__all__ = ["BACKEND_MODULE", "PROJECT_TEMPLATES", "SERVICES_COMPOSE"]
