"""Render the settings surface as the operator-facing reference page.

The page is generated, never hand-edited: ``.env.example`` had drifted to
document variables the code no longer binds, and a hand-written reference for
500-odd settings would rot the same way.
"""

from __future__ import annotations

from collections import OrderedDict
from collections.abc import Iterable

from scripts.config_surface.introspect import Setting

BANNER = "<!-- GENERATED by scripts/check_config_surface.py --write. Do not edit. -->"

PREAMBLE = """# Configuration reference

Every setting BaselithCore reads, generated from the `BaseSettings` classes that
declare them.

## Minimum to start

No field is declared *required* — each one carries a default — but validators
enforce combinations across fields. With a completely empty environment the
security configuration refuses to build:

```text
Value error, SECRET_KEY is required when AUTH_REQUIRED=true
```

So a deployment sets one variable, and every settings class builds:

```bash
SECRET_KEY=$(python -c "import secrets; print(secrets.token_urlsafe(64))")
```

Two more are worth setting immediately, though neither blocks startup:

- `APP_BASE_URL` — binds issued JWTs to this deployment. Without it (or an
  explicit `JWT_ISSUER` + `JWT_AUDIENCE`) a token minted by another environment
  that shares `SECRET_KEY` is accepted here.
- `APP_ENV` — gates every fail-closed control. An unrecognised name is treated
  as production, so declare a known one (`development`, `staging`, `test`, ...)
  to opt out.

For purely local work, `AUTH_REQUIRED=false` replaces `SECRET_KEY`. Everything
else on this page has a working default: set it only to change behaviour.

## Where values come from

Later sources win:

1. field defaults (this page);
2. the repository `.env`, loaded once at import time;
3. the process environment;
4. a secret read through the secrets provider, when the variable names one
   (`SECRETS_BACKEND=file` plus `SECRETS_DIR` resolves `NAME` from
   `<SECRETS_DIR>/NAME`, the Docker/Kubernetes convention).

Keep `.env` for local development. In production prefer real environment
variables for configuration and mounted files for secrets, so credentials never
sit in a file that a backup, an image layer or a stray `cat` can spread.

Values marked :material-key: are secrets: they are held as `SecretStr`, so they
are masked in logs, tracebacks and error reporting.

A variable that resembles a setting without matching one binds nothing and is
silently ignored; `baselith config env` reports those.
"""

LEGEND = {
    "columns": "| Variable | Type | Default | Description |",
    "rule": "| --- | --- | --- | --- |",
}


def _markdown(text: str) -> str:
    """Docstring prose is written in reStructuredText; the page is Markdown."""
    return text.replace("``", "`")


def _escape(text: str) -> str:
    return _markdown(text).replace("|", "\\|")


def _default_cell(setting: Setting) -> str:
    if setting.default == "required":
        return "**required**"
    if setting.default == "computed":
        return "_computed_"
    if setting.default == "":
        return "_empty_"
    return f"`{_escape(setting.default)}`"


def _variable_cell(setting: Setting) -> str:
    marker = " :material-key:" if setting.secret else ""
    cell = f"`{setting.env}`{marker}"
    if setting.alternatives:
        also = ", ".join(f"`{name}`" for name in setting.alternatives)
        cell += f"<br>also accepts {also}"
    return cell


def _row(setting: Setting) -> str:
    return (
        f"| {_variable_cell(setting)} "
        f"| `{_escape(setting.type_label)}` "
        f"| {_default_cell(setting)} "
        f"| {_escape(setting.description)} |"
    )


def _group(settings: Iterable[Setting]) -> OrderedDict[str, list[Setting]]:
    grouped: OrderedDict[str, list[Setting]] = OrderedDict()
    for setting in settings:
        grouped.setdefault(setting.section, []).append(setting)
    return grouped


def render_reference(settings: Iterable[Setting]) -> str:
    """The full Markdown page for ``settings``."""
    ordered = sorted(settings, key=lambda s: (s.module, s.class_name, s.env))
    lines = [BANNER, "", PREAMBLE.rstrip(), ""]
    for section, group in _group(ordered).items():
        lines += [f"## {_markdown(section)}", ""]
        modules = sorted({item.module for item in group})
        lines += [f"Declared in `{'`, `'.join(modules)}`.", ""]
        lines += [LEGEND["columns"], LEGEND["rule"]]
        lines += [_row(item) for item in group]
        lines.append("")
    lines += [
        "## Auditing your environment",
        "",
        "```bash",
        "baselith config env        # unknown or misspelled variables in the environment",
        "baselith doctor            # connectivity and configuration diagnostics",
        "```",
        "",
        f"{len(ordered)} settings documented.",
        "",
    ]
    return "\n".join(lines)
