"""BaselithCore Python SDK — a typed client for the BaselithCore API."""

from ._pagination import aiter_pages, iter_pages
from .client import AsyncBaselithClient, BaselithClient, ChatStreamError
from .errors import (
    APIConnectionError,
    AuthenticationError,
    BaselithAPIError,
    BaselithConfigError,
    BaselithError,
    NotFoundError,
    PermissionError_,
    RateLimitError,
    RunTimeoutError,
    ServerError,
)
from .models import (
    AgentRunRequest,
    AgentRunStatus,
    AgentRunSubmission,
    ApprovalDecisionRequest,
    ApprovalDecisionResult,
    ApprovalPage,
    ChatRequest,
    ChatResponse,
    FeedbackRequest,
    HealthStatus,
    Page,
    PendingApproval,
    ReadinessStatus,
    RunEvent,
    RunHistoryPage,
    RunResumeResult,
    WebhookCreated,
    WebhookCreateRequest,
    WebhookDelivery,
    WebhookDeliveryPage,
    WebhookEndpoint,
    WebhookPage,
    WebhookReplay,
)
from .version import __version__

__all__ = [
    "BaselithClient",
    "AsyncBaselithClient",
    "ChatStreamError",
    "iter_pages",
    "aiter_pages",
    "ChatRequest",
    "ChatResponse",
    "FeedbackRequest",
    "HealthStatus",
    "ReadinessStatus",
    "AgentRunRequest",
    "AgentRunSubmission",
    "AgentRunStatus",
    "RunEvent",
    "Page",
    "RunHistoryPage",
    "PendingApproval",
    "ApprovalPage",
    "ApprovalDecisionRequest",
    "ApprovalDecisionResult",
    "RunResumeResult",
    "WebhookEndpoint",
    "WebhookCreateRequest",
    "WebhookCreated",
    "WebhookPage",
    "WebhookDelivery",
    "WebhookDeliveryPage",
    "WebhookReplay",
    "BaselithError",
    "BaselithConfigError",
    "BaselithAPIError",
    "AuthenticationError",
    "PermissionError_",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "APIConnectionError",
    "RunTimeoutError",
    "__version__",
]
